name: "Branch build"

on: [push]

jobs:
  spotbugs-report-to-github:
    runs-on: ubuntu-latest
    name: "Spotbugs static analysis"
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 15
          architecture: x64
      - name: Cache Maven packages
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2
          key: ubuntu-latest-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-latest-m2
      
      #Running SpotBugs
      - name: Running 
        run: mvn clean install com.github.spotbugs:spotbugs-maven-plugin:spotbugs -Dspotbugs.sarifOutput=true -Dspotbugs.sarifFullPath=true -DskipTests
      
      #Merging sarif files
      - name: Installing SARIF multitool
        run: npm i -g @microsoft/sarif-multitool
      - name: Installing SARIF multitool
        run: sarif-multitool merge --recurse --merge-runs --force spotbugsSarif.json

      #
      - name: Debug
        run: ls -ls && ls -ls merged.sarif

      #Uploading sarif report
      - name: Upload report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: merged.sarif
